# 添加各个小节的子目录
add_subdirectory(01_depth_testing)
add_subdirectory(02_stencil_testing)
add_subdirectory(03_blending)
add_subdirectory(04_face_culling)
add_subdirectory(05_framebuffer)
add_subdirectory(06_cubemaps)
add_subdirectory(07_advanced_data)
add_subdirectory(08_advanced_glsl)
add_subdirectory(09_geometry_shader)
add_subdirectory(10_instancing)
add_subdirectory(11_anti_aliasing)
